# Generated by Django 4.2.7 on 2025-12-26 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patienthistorysnapshot",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Patient History Snapshot",
                "verbose_name_plural": "Patient History Snapshots",
            },
        ),
        migrations.AlterField(
            model_name="patienthistorysnapshot",
            name="json_data",
            field=models.JSONField(help_text="Complete history data in JSON format"),
        ),
        migrations.AlterField(
            model_name="patienthistorysnapshot",
            name="user",
            field=models.ForeignKey(
                help_text="User whose history is being snapshotted",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_snapshots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="patienthistorysnapshot",
            index=models.Index(
                fields=["user", "-created_at"], name="history_pat_user_id_bd0195_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="patienthistorysnapshot",
            table="history_patienthistorysnapshot",
        ),
    ]
