# Generated by Django 4.2.7 on 2025-12-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_professional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_type',
            field=models.CharField(blank=True, choices=[('psychiatrist', 'Psychiatrist'), ('therapist', 'Therapist'), ('psychologist', 'Psychologist')], max_length=50, null=True),
        ),
    ]
