# Generated by Django 4.2.7 on 2025-12-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_is_professional_user_professional_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True, help_text="Display name shown to others", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_anonymous_mode",
            field=models.BooleanField(
                default=True, help_text="User prefers anonymous mode"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_professional",
            field=models.BooleanField(
                default=False, help_text="Is this user a mental health professional?"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="professional_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("psychiatrist", "Psychiatrist"),
                    ("therapist", "Therapist"),
                    ("psychologist", "Psychologist"),
                ],
                help_text="Type of professional (only if is_professional=True)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="accounts_user",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
