# Generated by Django 4.2.7 on 2025-12-27 16:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_options_alter_user_display_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_anonymous_mode",
        ),
    ]
