# Generated by Django 4.2.7 on 2025-12-26 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="chatsession",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
            },
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="content_encrypted",
            field=django_cryptography.fields.encrypt(
                models.TextField(help_text="Encrypted message content")
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("bot", "Bot"),
                    ("professional", "Professional"),
                ],
                help_text="Who sent this message",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                help_text="Chat session this message belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chatsession",
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("escalated", "Escalated"),
                    ("closed", "Closed"),
                ],
                default="open",
                help_text="Current status of the chat session",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="user",
            field=models.ForeignKey(
                help_text="User participating in this chat session",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="chat_chatme_session_70d41b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "-created_at"], name="chat_chatse_user_id_47c665_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["status"], name="chat_chatse_status_97fce8_idx"),
        ),
        migrations.AlterModelTable(
            name="chatmessage",
            table="chat_chatmessage",
        ),
        migrations.AlterModelTable(
            name="chatsession",
            table="chat_chatsession",
        ),
    ]
