# Generated by Django 4.2.7 on 2025-12-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_chatmessage_options_alter_chatsession_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="risk_score",
            field=models.FloatField(
                blank=True, help_text="Risk score for this message (0-100)", null=True
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sentiment_score",
            field=models.FloatField(
                blank=True,
                help_text="Sentiment score for this message (-1.0 to +1.0)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="used_sop_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="IDs of SOP documents used to generate bot response (for auditing)",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="active_sop_categories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="SOP categories that have been used in this session",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="conversation_state",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Conversation context: topics, sentiment trend, risk trend, asked questions, active SOP category",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="max_risk_score",
            field=models.FloatField(
                default=0.0,
                help_text="Highest risk score encountered in this session (0-100)",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="sentiment_trend",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Sentiment scores over time in this session",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="session_summary",
            field=models.TextField(
                blank=True,
                help_text="Short bullet summary for professionals, updated as chat progresses",
            ),
        ),
    ]
