# Generated by Django 4.2.7 on 2025-12-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_chatmessage_risk_score_chatmessage_sentiment_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="is_anonymous",
            field=models.BooleanField(
                default=False,
                help_text="Whether this chat session is in anonymous mode",
            ),
        ),
    ]
