# Generated by Django 4.2.7 on 2025-12-26 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkin_mood", models.CharField(blank=True, max_length=50)),
                (
                    "checkin_intensity",
                    models.FloatField(default=0.0, help_text="0.0 to 1.0"),
                ),
                (
                    "text_encrypted",
                    django_cryptography.fields.encrypt(models.TextField()),
                ),
                (
                    "transcription_encrypted",
                    django_cryptography.fields.encrypt(models.TextField(blank=True)),
                ),
                (
                    "voice_file",
                    models.FileField(blank=True, null=True, upload_to="voice_uploads/"),
                ),
                ("ai_summary", models.TextField(blank=True)),
                (
                    "sentiment_score",
                    models.FloatField(default=0.0, help_text="-1.0 to +1.0"),
                ),
                (
                    "intensity_score",
                    models.FloatField(default=0.0, help_text="0.0 to 1.0"),
                ),
                ("key_themes", models.JSONField(blank=True, default=list)),
                ("risk_flags", models.JSONField(blank=True, default=dict)),
                ("suggest_start_chat", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Journal Entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
