# Generated by Django 4.2.7 on 2025-12-26 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalentry",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
            },
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="voice_file",
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="ai_summary",
            field=models.TextField(
                blank=True, help_text="AI-generated summary of the entry"
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="checkin_intensity",
            field=models.FloatField(
                default=0.0, help_text="Mood intensity: 0.0 to 1.0"
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="checkin_mood",
            field=models.CharField(
                blank=True, help_text="User's mood at time of entry", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="intensity_score",
            field=models.FloatField(
                default=0.0, help_text="Emotional intensity: 0.0 to 1.0"
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="key_themes",
            field=models.JSONField(
                blank=True, default=list, help_text="List of key themes identified"
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="risk_flags",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Risk flags detected (e.g., suicidal_ideation)",
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="sentiment_score",
            field=models.FloatField(
                default=0.0, help_text="Sentiment: -1.0 (negative) to +1.0 (positive)"
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="suggest_start_chat",
            field=models.BooleanField(
                default=False, help_text="AI suggests starting a chat session"
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="text_encrypted",
            field=django_cryptography.fields.encrypt(
                models.TextField(help_text="Encrypted journal entry text")
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="transcription_encrypted",
            field=django_cryptography.fields.encrypt(
                models.TextField(
                    blank=True,
                    help_text="Original transcription if different from text",
                )
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="user",
            field=models.ForeignKey(
                help_text="User who created this journal entry",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["user", "-created_at"], name="journal_jou_user_id_1ad335_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["created_at"], name="journal_jou_created_41a2c3_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="journalentry",
            table="journal_journalentry",
        ),
    ]
