# Generated by Django 4.2.7 on 2025-12-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_alter_journalentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="detected_emotions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of detected emotions with confidence scores",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="sentiment_label",
            field=models.CharField(
                default="neutral",
                help_text="Sentiment label: positive, neutral, or negative",
                max_length=20,
            ),
        ),
    ]
