# Generated by Django 4.2.7 on 2025-12-26 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("professionals", "0002_alter_escalationticket_options_and_more"),
        ("consent", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consentgrant",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Consent Grant",
                "verbose_name_plural": "Consent Grants",
            },
        ),
        migrations.AlterField(
            model_name="consentgrant",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Is this consent currently active? (Cannot be revoked in MVP)",
            ),
        ),
        migrations.AlterField(
            model_name="consentgrant",
            name="professional",
            field=models.ForeignKey(
                help_text="Professional receiving consent",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_grants",
                to="professionals.professional",
            ),
        ),
        migrations.AlterField(
            model_name="consentgrant",
            name="user",
            field=models.ForeignKey(
                help_text="User granting consent",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_grants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="consentgrant",
            index=models.Index(
                fields=["user", "active"], name="consent_con_user_id_e6bb0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consentgrant",
            index=models.Index(
                fields=["professional", "active"], name="consent_con_profess_df229f_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="consentgrant",
            table="consent_consentgrant",
        ),
    ]
