# Generated by Django 4.2.7 on 2025-12-26 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_alter_chatmessage_options_alter_chatsession_options_and_more"),
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="escalationticket",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Escalation Ticket",
                "verbose_name_plural": "Escalation Tickets",
            },
        ),
        migrations.AlterModelOptions(
            name="professional",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Professional",
                "verbose_name_plural": "Professionals",
            },
        ),
        migrations.AlterModelOptions(
            name="professionalsopdoc",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Professional SOP Document",
                "verbose_name_plural": "Professional SOP Documents",
            },
        ),
        migrations.AlterField(
            model_name="escalationticket",
            name="assigned_professional",
            field=models.ForeignKey(
                help_text="Professional assigned to review this ticket",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tickets",
                to="professionals.professional",
            ),
        ),
        migrations.AlterField(
            model_name="escalationticket",
            name="professional_notes",
            field=models.TextField(
                blank=True, help_text="Notes from the reviewing professional"
            ),
        ),
        migrations.AlterField(
            model_name="escalationticket",
            name="reason",
            field=models.TextField(help_text="Reason for escalation"),
        ),
        migrations.AlterField(
            model_name="escalationticket",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, help_text="When was this ticket reviewed?", null=True
            ),
        ),
        migrations.AlterField(
            model_name="escalationticket",
            name="session",
            field=models.ForeignKey(
                help_text="Chat session that triggered this escalation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escalation_tickets",
                to="chat.chatsession",
            ),
        ),
        migrations.AlterField(
            model_name="escalationticket",
            name="user",
            field=models.ForeignKey(
                help_text="User who needs professional review",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escalation_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="availability",
            field=models.TextField(
                blank=True, help_text="Professional availability schedule"
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="City where professional practices",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="specialization",
            field=models.CharField(
                help_text="Area of specialization (e.g., Anxiety, Depression)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="user",
            field=models.OneToOneField(
                help_text="User account linked to this professional profile",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professional_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="verified",
            field=models.BooleanField(
                default=False, help_text="Has this professional been verified?"
            ),
        ),
        migrations.AlterField(
            model_name="professionalsopdoc",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Is this SOP currently active?"
            ),
        ),
        migrations.AlterField(
            model_name="professionalsopdoc",
            name="category",
            field=models.CharField(
                help_text="Category (e.g., anxiety, depression, self-harm-risk, panic)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="professionalsopdoc",
            name="content",
            field=models.TextField(help_text="SOP content/guidelines"),
        ),
        migrations.AlterField(
            model_name="professionalsopdoc",
            name="created_by_professional",
            field=models.ForeignKey(
                help_text="Professional who created this SOP",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sop_docs",
                to="professionals.professional",
            ),
        ),
        migrations.AlterField(
            model_name="professionalsopdoc",
            name="title",
            field=models.CharField(
                help_text="Title of the SOP document", max_length=200
            ),
        ),
        migrations.AddIndex(
            model_name="escalationticket",
            index=models.Index(
                fields=["status", "-created_at"], name="professiona_status_7787c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="escalationticket",
            index=models.Index(
                fields=["assigned_professional", "status"],
                name="professiona_assigne_380e1e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="professionalsopdoc",
            index=models.Index(
                fields=["category", "active"], name="professiona_categor_590b92_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="escalationticket",
            table="professionals_escalationticket",
        ),
        migrations.AlterModelTable(
            name="professional",
            table="professionals_professional",
        ),
        migrations.AlterModelTable(
            name="professionalsopdoc",
            table="professionals_professionalsopdoc",
        ),
    ]
