# Generated by Django 4.2.7 on 2025-12-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_allow_blank_specialization_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='degree_picture',
            field=models.ImageField(blank=True, help_text='Degree certificate for therapists/psychologists', null=True, upload_to='professional_degrees/'),
        ),
        migrations.AddField(
            model_name='professional',
            name='pmdc_id',
            field=models.CharField(blank=True, default='', help_text='PMDC ID for psychiatrists', max_length=100),
        ),
        migrations.AddField(
            model_name='professional',
            name='professional_type',
            field=models.CharField(blank=True, choices=[('psychiatrist', 'Psychiatrist'), ('therapist', 'Therapist'), ('psychologist', 'Psychologist')], default='', help_text='Type of professional (psychiatrist, therapist, psychologist)', max_length=50),
        ),
        migrations.AddField(
            model_name='professional',
            name='university_name',
            field=models.CharField(blank=True, default='', help_text='University name for therapists/psychologists', max_length=200),
        ),
    ]
