# Generated by Django 4.2.7 on 2025-12-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0004_professional_degree_picture_professional_pmdc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Professional practice location', max_length=255),
        ),
        migrations.AddField(
            model_name='professional',
            name='session_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Session fee in local currency', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='years_of_experience',
            field=models.IntegerField(blank=True, help_text='Years of professional experience', null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='availability',
            field=models.TextField(blank=True, help_text='Professional availability schedule (JSON format for weekly schedule)'),
        ),
    ]
